### PR TITLE
Remove usage of InternalFrameList

### PR DESCRIPTION
**Pull request by lehnerpat**
Remove usage of InternalFrameList which was introduced in commit a329a7b92 when
the internal frame menu items were converted from radio buttons to normal menu
items.
Remove code related to changing the `selected` status of those menu items,
since they no longer display that status.
Remove InternalFrameList and RadioButtonList, since they are no longer used.
Fix some minor whitespace and style stuff in the touched files.

### CODE REVIEW

**Comment by smetzlaff** [comment]
I've kept the structures of the checkboxes, because I'm not really sure if they are useful. Since there are a lot of windows and the user might wish to know which is already open and which one is missing. However, by intuition a checkbox does not seem to be a good indicator for open windows.

**Comment by lehnerpat** [comment]
Well, the checkboxes could be used as indicators until some replacement for them is implemented (e.g. a toolbar with toggle buttons).

I just removed them because I did not see any checkboxes in my menus, so I assumed that was just leftover code from removing them.

**Comment by lehnerpat** [comment]
On a side note, other applications dont have a list of open frames (notably Eclipse, which was a great many "Views" as they're called). Of course, this is no good reason to not do it either, but I thought it's worth pointing out that users live without an open-frame indicator in even larger applications.

**Comment by smetzlaff** [comment]
Yes, that is basically also my opinion. By the way, using checkboxes would probably cause more confusion that it would help. I'll pull your code, when I find the time to look over it.

**Pull request merged**
